### ISSUE TITLE
Jan 2015 Deploy

### ISSUE THREAD

**Issue by evertsd** [MustWin/irregardless-docs-addon#43]
Removed #! from routes
Updated styles to match redesign

![screen shot 2015-01-22 at 11 27 51 pm](https://cloud.githubusercontent.com/assets/903050/5870264/5805bf02-a28f-11e4-88dc-e8e187a4fd48.png)

![screen shot 2015-01-22 at 11 28 12 pm](https://cloud.githubusercontent.com/assets/903050/5870257/224b0976-a28f-11e4-9dbc-fdc14756a8d0.png)

**Comment by dylanjha** [comment]
QA:

Functionality works, I think the bottom icon will need replacing and possibly the red texts
