### ISSUE TITLE
Question: Checking against Other Style Guides

### ISSUE THREAD

**Issue by tenji240** [MustWin/irregardless-docs-addon#44]
Two questions: 
- When searching for a style guide, are private style guides searchable?
- If a have a private style guide url i got from another user, how would I check my writing against that style guide?

**Comment by evertsd** [comment]
Those are good questions, as for the second point I don't believe theres a way to do that in the docs app, how do you do it in the regular app?

**Comment by tenji240** [comment]
We can have an input section for that. Maybe when the user input in the url, we strip the collection_id number and pass that into the api, and load that style guide.

**Comment by tenji240** [comment]
Close in #46
