### ISSUE TITLE
Pressing "Clear" should clear all the highlights in the document

### ISSUE THREAD

**Issue by frankiecheung** [MustWin/irregardless-docs-addon#49]
It currently clears the tips in the sidebar (if any were detected), but the highlights in the actual document remain.

Not clearing the highlights also results in states where the highlights expand themselves as I edit the text near the highlights.

**Comment by tenji240** [comment]
Hmm this worked out for me [ http://recordit.co/4OVuFrksdl ], but I'll see if can replicate it to where it doesn't work.

**Comment by tenji240** [comment]
Was able to recreated it. When you activate a suggested replacement, then select clear, the highlights are persisted.
