### ISSUE TITLE
Private style guide usage is inconsistent with emailed directions.

### ISSUE THREAD

**Issue by frankiecheung** [MustWin/irregardless-docs-addon#51]
In the email, it says:

"To access your guide from our Google Docs and Microsoft Word plugins, use this passcode: 2-4_iKGzy4qiRL4IVxhKbg"

In the plugin, it says to paste a private style guide URL to use the guide. Let's fix the emailed directions so that it's consistent.

**Comment by tenji240** [comment]
Going to move this to MustWin/Redpen
