### ISSUE TITLE
Private style guide name (bottom of screen) is incorrect?

### ISSUE THREAD

**Issue by frankiecheung** [MustWin/irregardless-docs-addon#52]
I pasted this into the settings, which is one of my private style guides that was created based on "Editor's Picks":
http://irregardless.ly/style_guides/337?code=2-4_iKGzy4qiRL4IVxhKbg

When it ran, it the tips seem to be flagged correctly, but on the bottom it says it's using "Editor's Choice" (which is neither "Editor's Picks" nor "Frankie's New Guide"), so not sure what's going on there.

![screen shot 2015-07-15 at 12 56 59 pm](https://cloud.githubusercontent.com/assets/10818293/8704490/465ebc3c-2af1-11e5-9744-8a3686cff6e8.png)

**Comment by tenji240** [comment]
Double checked this today: https://github.com/MustWin/irregardless-docs-addon/commit/422af8bda7b0678242a48f5d7583ae4ca2cbc000 seems to be working. I also ran my test suite against your guide, and I'm getting an error returned from the search service, so I'm looking into that. But the footer updates for the rest of these guides: https://github.com/MustWin/irregardless-docs-addon/blob/App-Submit-2/Code.gs#L202

**Comment by tenji240** [comment]
oh also, btw the error from earlier is related to this tip [http://irregardless.ly/tip/335] triggering shims, but returned a null pointer. the fix will come in with the rest of the search service updates.
